spring:
  application:
    name: tee-union-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/teeunion
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000
project:
  version: @project.version@